ALL_BUILD.vcxproj
ALL_BUILD.vcxproj.filters
appveyor.yml
bootstrap.py
build
build.ninja
build_log_perftest.vcxproj
build_log_perftest.vcxproj.filters
build-cmake
buildit.sh
buildit.sh~
canon_perftest.vcxproj
canon_perftest.vcxproj.filters
cleanit.sh
clparser_perftest.vcxproj
clparser_perftest.vcxproj.filters
cmake_install.cmake
CMakeCache.txt
CMakeFiles
CMakeLists.txt
configure.py
CONTRIBUTING.md
COPYING
CTestTestfile.cmake
depfile_parser_perftest.vcxproj
depfile_parser_perftest.vcxproj.filters
doc
hash_collision_bench.vcxproj
hash_collision_bench.vcxproj.filters
libninja.vcxproj
libninja.vcxproj.filters
libninja-re2c.vcxproj
libninja-re2c.vcxproj.filters
manifest_parser_perftest.vcxproj
manifest_parser_perftest.vcxproj.filters
misc
ninja.sln
ninja.vcxproj
ninja.vcxproj.filters
ninja_test.vcxproj
ninja_test.vcxproj.filters
platform_helper.pyc
README.md
RELEASING
RUN_TESTS.vcxproj
RUN_TESTS.vcxproj.filters
src
vc140.pdb
ZERO_CHECK.vcxproj
ZERO_CHECK.vcxproj.filters
